/**
 * SensorMap — the interactive Leaflet map at the heart of AgriSense.
 *
 * Renders every sensor as a coloured/sized "glyph" marker (colour and
 * size each encode either temperature or watermark, depending on
 * `glyphMode`), draws the Delaunay mesh/hull the backend computed, and
 * supports two interaction modes:
 *   - 'sensor': click markers to build a multi-sensor comparison selection
 *   - 'slice':  click markers or arbitrary map points to build an ordered
 *               cross-section path
 * It also drives a Windy-style scrollable timeline for scrubbing through
 * historical daily data, and an optional real-time barycentric colour
 * interpolation overlay (canvas) plus a cursor-following IDW (inverse
 * distance weighting) readout when hovering inside the sensor coverage hull.
 *
 * This file is organized top-to-bottom as:
 *   1. Small utilities (sorting, colour interpolation, distance math)
 *   2. Glyph styling (colour/size encoding logic)
 *   3. UI subcomponents (gradient legend, interpolation canvas, map click/hover handler)
 *   4. Main SensorMap component (data fetching + render)
 *   5. WindyTimeline subcomponent (the scrollable date scrubber)
 */
import React, { useState, useEffect, useRef, useMemo, useCallback } from 'react';
import { MapContainer, TileLayer, CircleMarker, Tooltip, Popup, useMapEvents, useMap, Polyline, Polygon } from 'react-leaflet';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';

// ─── UTILITY: Sort sensors FF-01 → FF-20 ───────────────────────────────────
export const sortSensorsById = (sensors) =>
    [...sensors].sort((a, b) => {
        const numA = parseInt((String(a.sensor_id || a.id || '')).match(/\d+/)?.[0] ?? '0', 10);
        const numB = parseInt((String(b.sensor_id || b.id || '')).match(/\d+/)?.[0] ?? '0', 10);
        return numA - numB;
    });

// ─── GLYPH STYLE: colour = temperature, radius = watermark ─────────────────
//
//  Both colour scales below are DYNAMIC: instead of fixed °C/cb anchor
//  points, each render computes the actual min/max of today's readings
//  (see computeDomain) and stretches the full colour sequence across that
//  exact range. This guarantees maximum separation between whatever values
//  are actually on screen — if every sensor reads within a narrow 14–18°C
//  band, that band now spans the *entire* colour sequence instead of one
//  washed-out slice of a fixed 2–26°C scale, so no two distinct readings
//  end up looking like "the same colour".
//
//  TEMP_BASE_COLORS is a dense 13-stop hue sweep — violet → magenta → red →
//  orange → gold — generated by rotating hue 265°→405° on the colour wheel.
//  That stays entirely on the "warm" side and never crosses the 45°-265°
//  band containing every green/cyan, which matters because a naive
//  blue→cyan→yellow scale actually blends THROUGH grass-green at its
//  midpoint — (0,188,212)→(255,235,59) passes through (128,212,136) — even
//  though neither endpoint is green. Every one of the 12 adjacent-stop
//  blends below was checked programmatically to confirm none of them ever
//  produces a green-dominant RGB triple at any interpolation point, and the
//  13-stop density means a real-world reading only 1-2°C apart from another
//  still lands on a visibly different colour instead of the same 4-8°C
//  bucket a sparser scale would collapse them into.
//
//  Watermark radius scale (centibars) — unchanged, still fixed buckets:
//    0–20   → radius 6   (very wet)
//    20–50  → radius 10
//    50–100 → radius 14
//    > 100  → radius 18  (very dry)
//

/**
 * Interpolates a value continuously across an array of [value, [r,g,b]]
 * stops (sorted ascending). Values outside the range clamp to the nearest
 * end colour rather than extrapolating.
 */
const interpolateColorScale = (value, stops) => {
    if (value <= stops[0][0]) return stops[0][1];
    const last = stops[stops.length - 1];
    if (value >= last[0]) return last[1];
    for (let i = 0; i < stops.length - 1; i++) {
        const [v0, c0] = stops[i];
        const [v1, c1] = stops[i + 1];
        if (value >= v0 && value <= v1) {
            const t = (value - v0) / (v1 - v0);
            return [
                Math.round(c0[0] + (c1[0] - c0[0]) * t),
                Math.round(c0[1] + (c1[1] - c0[1]) * t),
                Math.round(c0[2] + (c1[2] - c0[2]) * t),
            ];
        }
    }
    return last[1];
};

// Converts an [r, g, b] triple (0-255 each) to a "#rrggbb" hex string.
const rgbToHex = ([r, g, b]) => '#' + [r, g, b].map(v => v.toString(16).padStart(2, '0')).join('');

// Base colour sequences (evenly spaced along whatever domain is supplied).
const TEMP_BASE_COLORS = [
    [116, 32, 233],  // #7420E9 violet
    [155, 32, 233],  // #9B20E9
    [194, 32, 233],  // #C220E9 purple
    [233, 32, 233],  // #E920E9 magenta
    [233, 32, 194],  // #E920C2
    [233, 32, 155],  // #E9209B pink-magenta
    [233, 32, 116],  // #E92074
    [233, 32, 77],   // #E9204D rose
    [233, 32, 38],   // #E92026 red
    [233, 66, 32],   // #E94220
    [233, 105, 32],  // #E96920 orange-red
    [233, 144, 32],  // #E99020 orange
    [233, 183, 32],  // #E9B720 gold
];
const WATERMARK_BASE_COLORS = [
    [21, 101, 192],  // #1565C0 deep blue      — wet
    [106, 27, 154],  // #6A1B9A purple         — moist
    [230, 81, 0],    // #E65100 burnt orange   — dry
    [183, 28, 28],   // #B71C1C deep red       — very dry
];

const FALLBACK_TEMP_DOMAIN      = [2, 26];  // used only while data hasn't loaded yet
const FALLBACK_WATERMARK_DOMAIN = [0, 140];

// Spreads `colors` evenly across [min, max] to produce interpolateColorScale
// stops — this is what makes the palette dynamic per render.
const buildDynamicStops = (colors, domain) => {
    const [min, max] = domain;
    const span = max - min;
    const n = colors.length;
    if (!isFinite(span) || span <= 0) return colors.map((c, i) => [min + i * 0.001, c]); // degenerate guard
    return colors.map((c, i) => [min + (span * i) / (n - 1), c]);
};

// Scans today's sensor readings for `key` ('temp' | 'watermark') and returns
// a [min, max] domain, padded if every reading happens to be identical, or
// falling back to a static range if there's no data yet.
const computeDomain = (dayData, key, fallback) => {
    if (!dayData) return fallback;
    let min = Infinity, max = -Infinity;
    for (const entry of Object.values(dayData)) {
        const v = entry?.[key];
        if (v === null || v === undefined || !isFinite(v)) continue;
        if (v < min) min = v;
        if (v > max) max = v;
    }
    if (!isFinite(min) || !isFinite(max)) return fallback;
    if (min === max) {
        const pad = key === 'temp' ? 2 : 10;
        return [min - pad, max + pad];
    }
    return [min, max];
};

// Maps a temperature value to a hex colour on the (dynamic) temp scale.
// Returns neutral grey for missing/invalid values.
const getTempColor = (temp, domain = FALLBACK_TEMP_DOMAIN) => {
    if (temp === null || temp === undefined || !isFinite(temp)) return '#8a91a4';
    return rgbToHex(interpolateColorScale(temp, buildDynamicStops(TEMP_BASE_COLORS, domain)));
};

// Fixed-bucket marker radius for watermark (soil moisture tension):
// wetter soil (lower cb) gets a smaller marker, drier soil a larger one.
const getWatermarkRadius = (wm) => {
    if (wm === null || wm === undefined) return 6;
    if (wm <= 20)  return 6;
    if (wm <= 50)  return 10;
    if (wm <= 100) return 14;
    return 18;
};

// Mirrors getWatermarkRadius's bucketing, but keyed on temperature — used in
// 'watermark' glyph mode so that mode also carries a size dimension (larger
// = hotter), the same dual color+size encoding temp mode already has.
const getTempRadius = (temp) => {
    if (temp === null || temp === undefined) return 6;
    if (temp <= 6)  return 6;
    if (temp <= 14) return 10;
    if (temp <= 22) return 14;
    return 18;
};

// Maps a watermark value to a hex colour on the (dynamic) watermark scale.
const getWatermarkColor = (wm, domain = FALLBACK_WATERMARK_DOMAIN) => {
    if (wm === null || wm === undefined || !isFinite(wm)) return '#8a91a4';
    return rgbToHex(interpolateColorScale(wm, buildDynamicStops(WATERMARK_BASE_COLORS, domain)));
};


// mode: 'temp'      → colour=temperature, radius=watermark
//       'watermark' → colour=watermark,   radius=temperature
// Both modes now carry the same dual color+size encoding for consistency —
// whichever variable isn't driving colour drives marker size instead.
// A sensor entry may have temp=null or watermark=null if that channel had
// no valid readings on that day — the other channel may still be valid.
// We render with what we have rather than showing offline grey.
//
// dayData may carry three extra (non-API) fields added by the nearest-date
// fill step in SensorMap: __isStale (true if this reading isn't an exact
// match for currentDate — it was borrowed from the closest date that has
// one), __sourceDate (the date that borrowed reading actually came from),
// and __isFuture (true if that borrowed date is later than currentDate,
// false if it's earlier). `offline: true` now means "this sensor has no
// reading anywhere in the loaded date range" — genuinely nothing to show.
// A sensor with a gap around currentDate is `stale: true` instead, and is
// still rendered with its nearest known value so history isn't discarded.
/**
 * Computes the final marker style { color, radius, offline, stale } for
 * one sensor on one day, given the current glyph mode ('temp' or
 * 'watermark') and the live colour domains. See the large comment block
 * above for the full offline vs. stale distinction.
 */
const getGlyphStyle = (dayData, mode = 'temp', domains = {}) => {
    if (!dayData) return { color: '#8a91a4', radius: 6, offline: true, stale: false };
    const stale = !!dayData.__isStale;
    const tempDomain      = domains.temp      || FALLBACK_TEMP_DOMAIN;
    const watermarkDomain = domains.watermark || FALLBACK_WATERMARK_DOMAIN;
    if (mode === 'watermark') {
        // If watermark is null but temp exists, show a neutral small marker
        const col = dayData.watermark != null
            ? getWatermarkColor(dayData.watermark, watermarkDomain)
            : (dayData.temp != null ? '#8a91a4' : null);
        if (col === null) return { color: '#8a91a4', radius: 6, offline: true, stale: false };
        return { color: col, radius: getTempRadius(dayData.temp), offline: false, stale };
    }
    // temp mode — use temp for colour, watermark for size; fall back gracefully
    const col = dayData.temp != null
        ? getTempColor(dayData.temp, tempDomain)
        : (dayData.watermark != null ? '#8a91a4' : null);
    if (col === null) return { color: '#8a91a4', radius: 6, offline: true, stale: false };
    return {
        color:   col,
        radius:  getWatermarkRadius(dayData.watermark),  // returns 6 if null — fine
        offline: false,
        stale,
    };
};

// ─── HAVERSINE DISTANCE (km) ────────────────────────────────────────────────
// Great-circle distance between two lat/lon points, in kilometres.
// Used for IDW weighting (closer sensors get more influence) and for
// finding the nearest sensor to the cursor.
const getDistanceKm = (lat1, lon1, lat2, lon2) => {
    const R = 6371;
    const dLat = (lat2 - lat1) * Math.PI / 180;
    const dLon = (lon2 - lon1) * Math.PI / 180;
    const a = Math.sin(dLat/2)**2 +
              Math.cos(lat1*Math.PI/180) * Math.cos(lat2*Math.PI/180) * Math.sin(dLon/2)**2;
    return R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a));
};

// ─── POINT-IN-POLYGON (ray casting) ─────────────────────────────────────────
// Returns true if [lat, lng] lies inside the convex hull polygon.
// polygon is an array of [lat, lng] vertices in order.
const pointInPolygon = (lat, lng, polygon) => {
    if (!polygon || polygon.length < 3) return false;
    let inside = false;
    for (let i = 0, j = polygon.length - 1; i < polygon.length; j = i++) {
        const [yi, xi] = polygon[i];
        const [yj, xj] = polygon[j];
        const intersect = ((yi > lat) !== (yj > lat)) &&
            (lng < (xj - xi) * (lat - yi) / (yj - yi) + xi);
        if (intersect) inside = !inside;
    }
    return inside;
};

// ─── COLOUR UTILITIES FOR CANVAS INTERPOLATION ──────────────────────────────

// Parse "#rrggbb" → [r, g, b]
const hexToRgb = (hex) => {
    const h = hex.replace('#', '');
    return [parseInt(h.slice(0,2),16), parseInt(h.slice(2,4),16), parseInt(h.slice(4,6),16)];
};

// Convert numeric value to its legend colour using the same scale as getGlyphStyle
const valueToColor = (val, mode, domains = {}) =>
    mode === 'watermark' ? getWatermarkColor(val, domains.watermark || FALLBACK_WATERMARK_DOMAIN) : getTempColor(val, domains.temp || FALLBACK_TEMP_DOMAIN);

// ─── GRADIENT SCALE LEGEND ───────────────────────────────────────────────────
// Renders a continuous colour ramp bar (matching the canvas interpolation
// fill exactly) with evenly-spaced value labels — one per colour stop — so
// the legend reads as a smooth gradient with discrete labelled checkpoints,
// the same way the glyph dots and interpolation fill are actually coloured.
const GradientScale = ({ colors, labels, height = 14 }) => (
    <div>
        <div style={{
            height, borderRadius:'3px',
            background:`linear-gradient(to right, ${colors.join(', ')})`,
            border:'1px solid rgba(0,0,0,0.15)',
        }}/>
        <div style={{ position:'relative', height:'12px', marginTop:'4px' }}>
            {labels.map((label, i) => {
                const pct = (i / (labels.length - 1)) * 100;
                const transform =
                    i === 0 ? 'translateX(0)' :
                    i === labels.length - 1 ? 'translateX(-100%)' :
                    'translateX(-50%)';
                return (
                    <span key={label} style={{ position:'absolute', left:`${pct}%`, transform, fontSize:'9px', color:'#777', whiteSpace:'nowrap' }}>
                        {label}
                    </span>
                );
            })}
        </div>
    </div>
);

// Generates `count` evenly-spaced labels across a [min, max] domain — used
// so the legend's tick labels always reflect today's *actual* value range
// rather than a static, possibly-stale set of numbers.
const domainLabels = (domain, count, decimals, suffix = '') => {
    const [min, max] = domain;
    const span = max - min;
    return Array.from({ length: count }, (_, i) => `${(min + (span * i) / (count - 1)).toFixed(decimals)}${suffix}`);
};

// ─── INTERPOLATION CANVAS OVERLAY ───────────────────────────────────────────
// Mounted into Leaflet's overlayPane (see the re-parenting effect below) so
// it stacks correctly beneath marker/tooltip/popup panes instead of as a
// bare sibling of the pane stack. On every map move/zoom it reprojects all
// Delaunay triangle vertices to pixel coords and repaints the canvas,
// filling each triangle with a smooth barycentric colour gradient that
// exactly matches the glyph legend colour scale.
/**
 * InterpolationCanvas — renders the smooth colour-gradient overlay that
 * fills each Delaunay triangle with a per-pixel barycentric blend of its
 * three vertex colours. Mounted as an absolutely-positioned <canvas>
 * sibling inside the Leaflet map, redrawn on every pan/zoom since the
 * pixel positions of the (lat, lon) triangle vertices change.
 *
 * Wrapped in React.memo since triangle data is expensive to redraw and
 * only needs to change when its actual inputs change.
 */
const InterpolationCanvas = React.memo(function InterpolationCanvas({ triangles, glyphMode, visible, domains, onDrawComplete }) {
    const map     = useMap();
    const canvasRef = useRef(null);

    // Move the canvas into Leaflet's own overlayPane instead of leaving it
    // as a bare sibling of the pane stack. Leaflet's panes share one
    // explicit z-index ladder it maintains itself (tilePane 200 <
    // overlayPane 400 < markerPane 600 < tooltipPane 650 < popupPane 700);
    // a canvas rendered outside that pane system doesn't reliably stack
    // against sensor tooltips/popups even with a matching zIndex style,
    // which is why the purple/blue fill was painting over the "FF-15"
    // label box. Re-parenting it into overlayPane guarantees it always
    // sits below every marker, tooltip, and popup.
    useEffect(() => {
        const canvas = canvasRef.current;
        const pane   = map.getPane('overlayPane');
        if (canvas && pane && canvas.parentNode !== pane) {
            pane.appendChild(canvas);
        }
    }, [map]);

    // Keep the draw function in a ref (rather than calling it directly)
    // so the `map.on(...)` event listener below always calls the latest
    // version without needing to re-subscribe on every render.
    const draw = useRef(() => {});

    draw.current = () => {
        const canvas = canvasRef.current;
        if (!canvas || !visible || !triangles.length) {
            if (canvas) canvas.getContext('2d').clearRect(0,0,canvas.width,canvas.height);
            onDrawComplete?.(); // nothing to paint, but the caller is still waiting to hear "done"
            return;
        }
        const size = map.getSize();
        canvas.width  = size.x;
        canvas.height = size.y;

        // overlayPane (which this canvas now lives inside, see above) is
        // positioned by Leaflet in its own "layer point" space and gets
        // shifted with a CSS transform as the map pans — it is NOT simply
        // pinned to the container's top-left like a bare sibling would be.
        // So the canvas has to be re-anchored to the current top-left
        // layer point on every redraw, and every vertex projected with
        // latLngToLayerPoint (not latLngToContainerPoint) relative to that
        // same anchor — otherwise the pane's own transform gets applied a
        // second time on top of the projection, and the fill drifts away
        // from the sensor markers it's supposed to align with.
        const topLeft = map.containerPointToLayerPoint([0, 0]);
        L.DomUtil.setPosition(canvas, topLeft);

        const ctx = canvas.getContext('2d');
        ctx.clearRect(0, 0, canvas.width, canvas.height);

        const W = canvas.width, H = canvas.height;
        if (W === 0 || H === 0) { onDrawComplete?.(); return; }

        // Single ImageData for the whole overlay — every triangle is rasterised
        // directly into it via true per-pixel barycentric interpolation. This
        // gives one continuous colour gradient across each triangle (matching
        // the glyph legend exactly at every vertex) with no visible facets or
        // sub-triangle seams, and no "minute triangle" mesh artefacts.
        const imageData = ctx.createImageData(W, H);
        const data = imageData.data; // starts fully transparent (all zeros)
        const ALPHA = 255; // overlay opacity, 0-255 — fully opaque so the interpolated hull fill isn't washed out

        // Signed edge function used for both the triangle area and the
        // per-pixel barycentric weights (Pineda's rasterisation test).
        const edge = (ax, ay, bx, by, px, py) => (px - ax) * (by - ay) - (py - ay) * (bx - ax);

        // Colour stops for the *current* mode/domain, computed once for the
        // whole draw call rather than per triangle or per pixel — glyphMode
        // and domains don't change mid-draw, so there's no need to rebuild
        // this inside the loop below.
        const stops = buildDynamicStops(
            glyphMode === 'watermark' ? WATERMARK_BASE_COLORS : TEMP_BASE_COLORS,
            glyphMode === 'watermark' ? (domains.watermark || FALLBACK_WATERMARK_DOMAIN) : (domains.temp || FALLBACK_TEMP_DOMAIN)
        );

        triangles.forEach(([v0, v1, v2]) => {
            const val0 = glyphMode === 'watermark' ? v0.watermark : v0.temp;
            const val1 = glyphMode === 'watermark' ? v1.watermark : v1.temp;
            const val2 = glyphMode === 'watermark' ? v2.watermark : v2.temp;
            if (val0 == null || val1 == null || val2 == null) return;

            // Project lat/lng → layer-point coords, then subtract the same
            // top-left anchor the canvas element itself was just moved to,
            // so a pixel drawn at e.g. (0,0) here lands under the canvas's
            // own (0,0) — matching how the canvas is actually positioned.
            const p0 = map.latLngToLayerPoint([v0.lat, v0.lon]).subtract(topLeft);
            const p1 = map.latLngToLayerPoint([v1.lat, v1.lon]).subtract(topLeft);
            const p2 = map.latLngToLayerPoint([v2.lat, v2.lon]).subtract(topLeft);

            const area = edge(p0.x, p0.y, p1.x, p1.y, p2.x, p2.y);
            if (Math.abs(area) < 1e-6) return; // degenerate (collinear) triangle

            const minX = Math.max(0, Math.floor(Math.min(p0.x, p1.x, p2.x)));
            const maxX = Math.min(W - 1, Math.ceil(Math.max(p0.x, p1.x, p2.x)));
            const minY = Math.max(0, Math.floor(Math.min(p0.y, p1.y, p2.y)));
            const maxY = Math.min(H - 1, Math.ceil(Math.max(p0.y, p1.y, p2.y)));
            if (minX > maxX || minY > maxY) return;

            for (let y = minY; y <= maxY; y++) {
                const py = y + 0.5;
                for (let x = minX; x <= maxX; x++) {
                    const px = x + 0.5;

                    // Barycentric weights for (px,py), normalised by triangle area.
                    // Dividing by area (rather than comparing raw edge signs)
                    // makes this orientation-agnostic — works for either winding.
                    const w0 = edge(p1.x, p1.y, p2.x, p2.y, px, py) / area;
                    const w1 = edge(p2.x, p2.y, p0.x, p0.y, px, py) / area;
                    const w2 = 1 - w0 - w1;

                    if (w0 < -1e-3 || w1 < -1e-3 || w2 < -1e-3) continue; // outside triangle

                    // Blend the underlying VALUE by barycentric weight, then map
                    // that single interpolated value through the colour scale —
                    // not the other way around. Blending three already-mapped
                    // RGB colours (the previous approach) is only equivalent to
                    // this for a plain 2-stop linear gradient; TEMP_BASE_COLORS
                    // and WATERMARK_BASE_COLORS are multi-stop, non-linear scales,
                    // so RGB-blending them produced a fill whose colour at a given
                    // pixel didn't correspond to that pixel's actual interpolated
                    // value on the same scale the legend and markers use — e.g. a
                    // pixel 95% of the way toward one vertex could still show a
                    // colour tinted from a hue two or three stops away. Mapping
                    // the blended value once guarantees a pixel exactly at a
                    // vertex renders in the vertex's own colour, and every other
                    // pixel's colour matches what that pixel's value would show
                    // on the legend.
                    const interpolatedVal = w0 * val0 + w1 * val1 + w2 * val2;
                    const [r, g, b] = interpolateColorScale(interpolatedVal, stops);

                    const idx = (y * W + x) * 4;
                    data[idx]     = r;
                    data[idx + 1] = g;
                    data[idx + 2] = b;
                    data[idx + 3] = ALPHA;
                }
            }
        });

        ctx.putImageData(imageData, 0, 0);
        onDrawComplete?.(); // the expensive per-pixel raster loop above has now actually finished painting
    };

    // Redraw whenever the underlying data/mode/visibility changes...
    useEffect(() => { draw.current(); }, [triangles, glyphMode, visible, domains]);

    // ...and also whenever the map itself moves/zooms/resizes, since the
    // canvas is drawn in screen-pixel space, not map (lat/lon) space.
    useEffect(() => {
        const redraw = () => draw.current();
        map.on('move zoom moveend zoomend resize', redraw);
        return () => map.off('move zoom moveend zoomend resize', redraw);
    }, [map]);

    return (
        <canvas
            ref={canvasRef}
            style={{ position:'absolute', top:0, left:0, pointerEvents:'none' }}
        />
    );
});  // end React.memo

// ─── MAP INTERACTION: click (slice mode) + hover IDW interpolation ──────────
// All frequently-changing values are passed as refs, not props, so that
// React never remounts this component (and drops Leaflet event listeners)
// when timeline data, hull polygon, or glyph mode updates.
/**
 * MapInteraction — invisible component that wires up Leaflet click/hover
 * events (must live inside <MapContainer> to use useMapEvents).
 *
 * - click: in 'slice' mode, reports the clicked lat/lng as a new waypoint.
 * - mousemove: computes a live inverse-distance-weighted (IDW) estimate
 *   of temperature/watermark at the cursor position (if inside the
 *   sensor coverage hull) and reports it via setInterpolatedData for the
 *   floating tooltip.
 *
 * All frequently-changing values are passed as refs, not props (see the
 * comment above the function signature), so this component never
 * remounts and Leaflet's event listeners stay attached.
 */
function MapInteraction({ modeRef, onMapClick, currentDayDataRef, setInterpolatedData, glyphModeRef, hullPolygonRef, tempDomainRef, watermarkDomainRef }) {
    const loggedRef = useRef(false); // one-shot diagnostic flag (was incorrectly self-referencing `mousemove`, which threw a ReferenceError on every move and silently killed the IDW tooltip before it could run)
    useMapEvents({
        click(e) {
            if (modeRef.current === 'slice') onMapClick(`${e.latlng.lat},${e.latlng.lng}`);
        },
        mousemove(e) {
            const currentDayData = currentDayDataRef.current;
            const hullPolygon    = hullPolygonRef.current;
            const glyphMode      = glyphModeRef.current;
            const effectiveMode  = glyphMode === 'interp' ? 'temp' : glyphMode;

            // ── One-shot diagnostic (remove after confirming IDW works) ──────
            if (!loggedRef.current) {
                loggedRef.current = true;
                console.debug('[IDW] First mousemove:', {
                    hasData:    !!currentDayData,
                    dataKeys:   currentDayData ? Object.keys(currentDayData).length : 0,
                    hullLen:    hullPolygon?.length ?? 0,
                    glyphMode,
                    sampleEntry: currentDayData ? Object.values(currentDayData).find(Boolean) : null,
                });
            }

            if (!currentDayData) { setInterpolatedData(null); return; }
            const { lat, lng } = e.latlng;

            const allEntries = Object.values(currentDayData).filter(s =>
                s && s.lat != null && s.lon != null
            );
            const tempSensors = allEntries.filter(s => s.temp      != null);
            const wmSensors   = allEntries.filter(s => s.watermark != null);
            if (!tempSensors.length && !wmSensors.length) { setInterpolatedData(null); return; }

            // ── Hull gate ────────────────────────────────────────────────────
            // Strict boundary: interpolated readings are only ever shown for
            // points inside the convex hull of sensor coverage. No fallback —
            // if the hull hasn't loaded yet (or has fewer than 3 vertices),
            // that's treated as "no valid coverage area" rather than
            // extrapolating from raw proximity to a sensor.
            if (!hullPolygon || hullPolygon.length < 3) { setInterpolatedData(null); return; }
            if (!pointInPolygon(lat, lng, hullPolygon)) { setInterpolatedData(null); return; }

            // IDW for temperature — each sensor's value is weighted by
            // 1/distance², so nearby sensors dominate the estimate. If the
            // cursor is essentially on top of a sensor, use its raw value
            // directly instead of a (numerically unstable) huge weight.
            let interpTemp = null;
            if (tempSensors.length) {
                let numT = 0, denT = 0;
                tempSensors.forEach(s => {
                    const d = getDistanceKm(lat, lng, s.lat, s.lon);
                    if (d < 0.001) { numT = s.temp; denT = 1; }
                    else if (denT !== 1) { const w = 1/d**2; numT += w*s.temp; denT += w; }
                });
                if (denT > 0) interpTemp = numT / denT;
            }

            // IDW for watermark
            let interpWatermark = null;
            if (wmSensors.length) {
                let numW = 0, denW = 0;
                wmSensors.forEach(s => {
                    const d = getDistanceKm(lat, lng, s.lat, s.lon);
                    if (d < 0.001) { numW = s.watermark; denW = 1; }
                    else if (denW !== 1) { const w = 1/d**2; numW += w*s.watermark; denW += w; }
                });
                if (denW > 0) interpWatermark = numW / denW;
            }

            // Nearest node distance across all sensors with any data
            let minDist = Infinity;
            allEntries.forEach(s => {
                const d = getDistanceKm(lat, lng, s.lat, s.lon);
                if (d < minDist) minDist = d;
            });

            if (interpTemp === null && interpWatermark === null) { setInterpolatedData(null); return; }

            const glyphColor  = effectiveMode === 'watermark'
                ? getWatermarkColor(interpWatermark, watermarkDomainRef.current)
                : getTempColor(interpTemp, tempDomainRef.current);
            const glyphRadius = effectiveMode === 'watermark' ? getTempRadius(interpTemp) : getWatermarkRadius(interpWatermark);
            setInterpolatedData({
                lat, lng,
                latStr: lat.toFixed(4), lngStr: lng.toFixed(4),
                temp:      interpTemp      != null ? interpTemp.toFixed(2)      : null,
                watermark: interpWatermark != null ? interpWatermark.toFixed(2) : null,
                nearestDist: (minDist * 0.621371).toFixed(2),
                glyphColor, glyphRadius,
                screenX: e.containerPoint.x, screenY: e.containerPoint.y,
            });
        },
        mouseout() { setInterpolatedData(null); },
    });
    return null;
}

// ─── MAIN COMPONENT ─────────────────────────────────────────────────────────
/**
 * @param {'sensor'|'slice'} mode - current selection mode from App.jsx
 * @param {string} dateFrom - ISO date, start of the timeline range to load
 * @param {string} dateTo - ISO date, end of the timeline range to load
 * @param {string[]} activeSensors - currently-selected sensor IDs / waypoints
 * @param {(id: string) => void} onSensorClick - called when a marker/map point is clicked
 * @param {(ids: string[]) => void} onSelectAll - called by the "Select All" button
 * @param {() => void} onClearAll - called by the "Clear" button
 */
export default function SensorMap({ mode, dateFrom, dateTo, activeSensors = [], onSensorClick, onSelectAll, onClearAll, onLoadingChange }) {
    const [timelineData,    setTimelineData]    = useState({}); // raw { date: { sensorId: {lat,lon,temp,watermark} } } from the API
    const [allSensors,      setAllSensors]      = useState([]); // master sensor list with coordinates
    const [dates,           setDates]           = useState([]); // sorted list of dates present in timelineData
    const [currentIndex,    setCurrentIndex]    = useState(0);  // index into `dates` the timeline is currently showing
    const [isPlaying,       setIsPlaying]       = useState(false); // timeline autoplay on/off
    const [playSpeed,       setPlaySpeed]       = useState(800);   // ms between autoplay steps
    const [interpolatedData,setInterpolatedData]= useState(null);  // live IDW readout under the cursor
    const [sortBy,          setSortBy]          = useState('name'); // sensor panel sort: 'name' or 'heartbeat'
    const [glyphMode,       setGlyphMode]       = useState('temp');  // which variable drives marker colour
    const [interpOn,        setInterpOn]        = useState(false);   // barycentric canvas overlay on/off
    const [meshEdges,       setMeshEdges]       = useState([]);   // Delaunay mesh wireframe edges
    const [hullPolygon,     setHullPolygon]     = useState([]);   // convex hull of sensor coverage
    const [triangles,       setTriangles]       = useState([]);   // Delaunay triangles (for the canvas fill)
    const [isLoading,       setIsLoading]       = useState(false); // true while fetchMapData is in flight
    const [isRendering,     setIsRendering]     = useState(false); // true from when fresh data lands until InterpolationCanvas has actually finished painting it
    // The loading cursor should stay up for the whole "still doing work"
    // window, not just the network round-trip: clearing isLoading the
    // instant fetch() resolves left a real gap where the cursor already
    // looked idle but the canvas's per-pixel raster loop (draw.current(),
    // above) hadn't run yet — a rendering delay the cursor was silently
    // lying about. isBusy covers both phases.
    const isBusy = isLoading || isRendering;
    const handleDrawComplete = useCallback(() => setIsRendering(false), []);
    const playIntervalRef    = useRef(null);
    const currentDayDataRef  = useRef(null);
    const hullPolygonRef     = useRef([]);
    const glyphModeRef       = useRef('temp');
    const modeRef            = useRef(mode);
    const wrapperRef         = useRef(null); // outer map div — used to keep the cursor-following IDW tooltip on-screen
    const tempDomainRef      = useRef(FALLBACK_TEMP_DOMAIN);
    const watermarkDomainRef = useRef(FALLBACK_WATERMARK_DOMAIN);

    // Bubble the loading state up to whoever's rendering us (App.jsx), so a
    // wait cursor can be applied outside the map too — the toolbar, sidebar,
    // and nav bar all live in App's tree, not this component's.
    useEffect(() => { onLoadingChange?.(isBusy); }, [isBusy, onLoadingChange]);

    // ── Fetch timeline + master sensor list ─────────────────────────────────
    // Loads five things whenever the date range changes: the per-day
    // timeline, the master sensor list, the Delaunay mesh edges, the
    // convex hull, and the full triangle set (for the fill overlay). Also
    // polls every 60s to pick up newly-arrived sensor readings.
    const isCompleteIsoDate = (d) => typeof d === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(d);
    useEffect(() => {
        // A native <input type="date"> fires onChange with an empty string
        // for every keystroke while it's being retyped and not yet a valid
        // date (e.g. mid-edit on the year), not just once the full date is
        // entered. Without this guard each of those intermediate changes
        // fires date_from=/date_to= with an empty or partial value, and the
        // backend correctly rejects it with 422 Unprocessable Content —
        // bailing out here just skips fetching until both dates are
        // complete again, instead of spamming failed requests while typing.
        if (!isCompleteIsoDate(dateFrom) || !isCompleteIsoDate(dateTo)) return;

        const fetchMapData = async () => {
            setIsLoading(true);
            try {
                const cb = Date.now(); // cache-busting query param
                const tlRes = await fetch(
                    `http://localhost:8000/sensors/timeline?date_from=${dateFrom}&date_to=${dateTo}&cb=${cb}`
                );
                if (!tlRes.ok) throw new Error(`Timeline ${tlRes.status}`);
                const tlData = await tlRes.json();
                setTimelineData(tlData);

                const sorted = Object.keys(tlData).sort();
                // Only trigger a state update (and reset currentIndex to
                // the latest date) if the actual set of dates changed —
                // avoids resetting the timeline scrubber position on every
                // 60s poll if nothing new has arrived.
                setDates(prev => {
                    if (JSON.stringify(prev) !== JSON.stringify(sorted)) {
                        setCurrentIndex(sorted.length ? sorted.length - 1 : 0);
                        return sorted;
                    }
                    return prev;
                });

                const msRes = await fetch(`http://localhost:8000/sensors?cb=${cb}`);
                if (!msRes.ok) throw new Error(`Sensors ${msRes.status}`);
                setAllSensors(sortSensorsById(await msRes.json()));

                const meshRes = await fetch(
                    `http://localhost:8000/sensors/mesh?date_from=${dateFrom}&date_to=${dateTo}&cb=${cb}`
                );
                if (meshRes.ok) {
                    const meshData = await meshRes.json();
                    setMeshEdges(meshData.edges || []);
                }

                const hullRes = await fetch(
                    `http://localhost:8000/sensors/hull?date_from=${dateFrom}&date_to=${dateTo}&cb=${cb}`
                );
                if (hullRes.ok) {
                    const hullData = await hullRes.json();
                    setHullPolygon(hullData.hull || []);
                }

                const triRes = await fetch(
                    `http://localhost:8000/sensors/triangles?date_from=${dateFrom}&date_to=${dateTo}&cb=${cb}`
                );
                if (triRes.ok) {
                    const triData = await triRes.json();
                    setTriangles(triData.triangles || []);
                }
            } catch (e) { console.error('Map fetch error:', e); }
            finally {
                setIsLoading(false);
                // The fetch is done, but new triangles/mesh data means the
                // canvas still has a potentially-expensive repaint ahead of
                // it (see InterpolationCanvas's draw effect below) — stay
                // "busy" until that reports back via onDrawComplete, rather
                // than dropping the cursor to idle while the page is still
                // visibly working.
                setIsRendering(true);
            }
        };
        fetchMapData();
        const poll = setInterval(fetchMapData, 60000);
        return () => clearInterval(poll);
    }, [dateFrom, dateTo]);

    // ── Autoplay metronome ───────────────────────────────────────────────────
    // When isPlaying is true, advance currentIndex one step every
    // `playSpeed` ms; auto-stops once it reaches the last date.
    useEffect(() => {
        if (isPlaying) {
            playIntervalRef.current = setInterval(() => {
                setCurrentIndex(prev => {
                    if (prev >= dates.length - 1) { setIsPlaying(false); return prev; }
                    return prev + 1;
                });
            }, playSpeed);
        } else {
            clearInterval(playIntervalRef.current);
        }
        return () => clearInterval(playIntervalRef.current);
    }, [isPlaying, dates.length, playSpeed]);

    // ── Node health list (for sensor panel) ─────────────────────────────────
    // Builds the sidebar list: for each sensor, finds its most recent date
    // with a valid temp reading (searching backwards through `dates`) to
    // use as "last heartbeat", then sorts either alphabetically by ID or
    // by recency of that heartbeat.
    const healthList = useMemo(() => {
        if (!allSensors.length || !dates.length) return [];
        return allSensors.map(sensor => {
            const rawId = sensor.sensor_id || sensor.id || 'UNKNOWN';
            let lastHeartbeat = null;
            for (let i = dates.length - 1; i >= 0; i--) {
                const dd = timelineData[dates[i]];
                if (dd) {
                    const nd = dd[rawId] || dd[String(rawId).toLowerCase()] || dd[String(rawId).toUpperCase()];
                    if (nd?.temp != null) { lastHeartbeat = dates[i]; break; }
                }
            }
            const num = parseInt(String(rawId).match(/\d+/)?.[0] ?? '0', 10);
            return { sid: rawId, displayId: `FF-${String(num).padStart(2,'0')}`, numericPart: num, lastHeartbeat };
        }).sort((a, b) => {
            if (sortBy === 'name') return a.numericPart - b.numericPart;
            const tA = a.lastHeartbeat ? new Date(a.lastHeartbeat).getTime() : 0;
            const tB = b.lastHeartbeat ? new Date(b.lastHeartbeat).getTime() : 0;
            return tA === tB ? a.numericPart - b.numericPart : tB - tA;
        });
    }, [allSensors, timelineData, dates, sortBy]);

    // ── Nearest-date-filled timeline (per-sensor closest available reading) ──
    // Fixes the "sensor shows no data" issue: previously a marker was only
    // rendered if timelineData[currentDate] had a literal entry for that
    // sensor, so any date the sensor didn't report on went blank even
    // though it has readings nearby. This now looks both backward (last
    // reading at/before currentDate) and forward (next reading at/after
    // currentDate) and picks whichever is closer in time to the date
    // actually being viewed, tagging it __isStale (not an exact match) and
    // __isFuture (whether the reading it borrowed comes from later than
    // currentDate) so the UI can label it correctly. A sensor only ends up
    // with no dayData at all if it has zero readings anywhere in the range.
    const forwardFilledData = useMemo(() => {
        if (!dates.length || !allSensors.length) return {};
        const ids = allSensors
            .map(s => s.sensor_id || s.id)
            .filter(Boolean);

        // Backward pass: most recent reading at or before each date.
        const lastSeen = {}; // rawId -> { data, date }
        const pastByDate = {};
        for (const date of dates) {
            const dd = timelineData[date] || {};
            const dayResult = {};
            for (const rawId of ids) {
                const entry = dd[rawId] || dd[String(rawId).toLowerCase()] || dd[String(rawId).toUpperCase()];
                if (entry) lastSeen[rawId] = { data: entry, date };
                dayResult[rawId] = lastSeen[rawId] || null;
            }
            pastByDate[date] = dayResult;
        }

        // Forward pass: soonest reading at or after each date.
        const nextSeen = {}; // rawId -> { data, date }
        const futureByDate = {};
        for (let i = dates.length - 1; i >= 0; i--) {
            const date = dates[i];
            const dd = timelineData[date] || {};
            const dayResult = {};
            for (const rawId of ids) {
                const entry = dd[rawId] || dd[String(rawId).toLowerCase()] || dd[String(rawId).toUpperCase()];
                if (entry) nextSeen[rawId] = { data: entry, date };
                dayResult[rawId] = nextSeen[rawId] || null;
            }
            futureByDate[date] = dayResult;
        }

        // Merge: for each date/sensor, keep whichever of the past/future
        // candidate is temporally closer to the date being viewed.
        const byDate = {};
        for (const date of dates) {
            const targetTime = new Date(date).getTime();
            const dayResult = {};
            for (const rawId of ids) {
                const past   = pastByDate[date][rawId];
                const future = futureByDate[date][rawId];
                let chosen = null;
                if (past && future) {
                    const pastDiff   = targetTime - new Date(past.date).getTime();
                    const futureDiff = new Date(future.date).getTime() - targetTime;
                    chosen = pastDiff <= futureDiff ? past : future;
                } else {
                    chosen = past || future;
                }
                dayResult[rawId] = chosen
                    ? { ...chosen.data, __isStale: chosen.date !== date, __sourceDate: chosen.date, __isFuture: chosen.date > date }
                    : null;
            }
            byDate[date] = dayResult;
        }
        return byDate;
    }, [dates, timelineData, allSensors]);

    const currentDate    = dates[currentIndex];
    const currentDayData = currentDate ? forwardFilledData[currentDate] : null;

    // Live colour domains — stretches the full palette across whatever range
    // of readings actually exists today, so a narrow real-world cluster
    // (e.g. everything reading 14-20°C) still spans the entire colour
    // sequence instead of collapsing into one washed-out slice of a fixed
    // 2-26°C scale. Recomputed only when the day's data actually changes.
    const tempDomain      = useMemo(() => computeDomain(currentDayData, 'temp', FALLBACK_TEMP_DOMAIN), [currentDayData]);
    const watermarkDomain = useMemo(() => computeDomain(currentDayData, 'watermark', FALLBACK_WATERMARK_DOMAIN), [currentDayData]);
    tempDomainRef.current      = tempDomain;
    watermarkDomainRef.current = watermarkDomain;

    // Keep refs in sync so MapInteraction always reads fresh values
    // without needing to remount when they change
    currentDayDataRef.current = currentDayData;
    hullPolygonRef.current    = hullPolygon;
    glyphModeRef.current      = glyphMode;
    modeRef.current           = mode;

    // ─── RENDER ─────────────────────────────────────────────────────────────
    return (
        <div ref={wrapperRef} style={{ position: 'relative', width: '100%', height: '100%', cursor: isBusy ? 'wait' : 'default' }}>

            {/* Live IDW readout — fixed in the top-left corner of the map
                while hovering the sensor coverage hull, showing the
                interpolated readings under the cursor. Anchored rather than
                cursor-following so it never drifts over the markers/mesh
                it's describing, or gets clipped near the map edges. */}
            {interpolatedData && (
                <div style={{ position:'absolute', top: 20, left: 20, zIndex:1000, backgroundColor: 'rgba(26,58,42,0.95)', color: '#eaddc4', padding: '15px', borderRadius: '8px', boxShadow: '0 8px 16px rgba(0,0,0,0.3)', pointerEvents: 'none', minWidth: '220px', border: '1px solid #4a6a5a' }}>
                    <div style={{ fontSize: '11px', fontWeight: 'bold', marginBottom: '10px', letterSpacing: '1px', borderBottom: '1px solid #4a6a5a', paddingBottom: '6px', display: 'flex', justifyContent: 'space-between' }}>
                        <span>LIVE SPATIAL ESTIMATE</span><span style={{ color: '#00e676' }}>●</span>
                    </div>
                    <div style={{ fontSize: '13px', marginBottom: '8px', fontFamily: 'monospace', color: '#a0bfa0' }}>{interpolatedData.latStr}, {interpolatedData.lngStr}</div>
                    <div style={{ fontSize: '15px', marginBottom: '4px', color: getTempColor(parseFloat(interpolatedData.temp), tempDomain) }}><strong>Temp:</strong> {interpolatedData.temp != null ? `${interpolatedData.temp}°C` : 'N/A'}</div>
                    <div style={{ fontSize: '15px', marginBottom: '4px', color: '#03A9F4' }}><strong>Watermark:</strong> {interpolatedData.watermark != null ? `${interpolatedData.watermark} cb` : 'N/A'}</div>
                    <div style={{ fontSize: '11px', color: '#888', marginTop: '10px', fontStyle: 'italic' }}>Nearest node: {interpolatedData.nearestDist} mi</div>
                </div>
            )}

            {/* Sensor node panel — top-right floating card listing every
                sensor with online/offline status, sortable by name or
                last-heartbeat, with Select All / Clear controls and a
                per-node click-to-toggle-selection row. */}
            <div style={{ position: 'absolute', top: 20, right: 20, zIndex: 1000, backgroundColor: 'rgba(255,255,255,0.97)', padding: '14px', borderRadius: '12px', boxShadow: '0 8px 24px rgba(0,0,0,0.15)', width: '275px', maxHeight: '75vh', display: 'flex', flexDirection: 'column', gap: '8px' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: '2px solid #eaeaea', paddingBottom: '10px' }}>
                    <strong style={{ color: '#1a3a2a', fontSize: '13px' }}>📡 SENSOR NODES</strong>
                    <div style={{ display: 'flex', gap: '4px', backgroundColor: '#e9ecef', padding: '3px', borderRadius: '4px' }}>
                        {['name','heartbeat'].map(s => (
                            <button key={s} onClick={() => setSortBy(s)} style={{ border: 'none', padding: '3px 7px', fontSize: '10px', fontWeight: 'bold', borderRadius: '3px', cursor: 'pointer', backgroundColor: sortBy===s ? 'white' : 'transparent', color: sortBy===s ? '#1a3a2a' : '#888', boxShadow: sortBy===s ? '0 1px 3px rgba(0,0,0,0.1)' : 'none' }}>{s==='name'?'A-Z':'TIME'}</button>
                        ))}
                    </div>
                </div>
                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                    <span style={{ fontSize: '11px', color: '#888', fontWeight: 'bold' }}>{activeSensors.length} selected</span>
                    <div style={{ display: 'flex', gap: '5px' }}>
                        <button onClick={() => onSelectAll?.(healthList.map(n=>n.sid))} style={{ padding: '4px 10px', fontSize: '10px', fontWeight: 'bold', border: 'none', borderRadius: '4px', cursor: 'pointer', backgroundColor: '#1a3a2a', color: 'white' }}>Select All</button>
                        <button onClick={() => onClearAll?.()} style={{ padding: '4px 10px', fontSize: '10px', fontWeight: 'bold', border: 'none', borderRadius: '4px', cursor: 'pointer', backgroundColor: '#e9ecef', color: '#555' }}>Clear</button>
                    </div>
                </div>
                <div style={{ display: 'flex', gap: '14px', fontSize: '10px', color: '#666', paddingBottom: '6px', borderBottom: '1px solid #f0f0f0' }}>
                    <span><span style={{ color: '#00e676' }}>●</span> Online</span>
                    <span><span style={{ color: '#FF5722' }}>●</span> Offline</span>
                    <span><span style={{ color: '#8a91a4' }}>●</span> No data</span>
                </div>
                <div style={{ overflowY: 'auto', flex: 1, paddingRight: '4px' }}>
                    {healthList.map(node => {
                        const isOnline  = dates.length > 0 && node.lastHeartbeat === dates[dates.length-1];
                        const dotColor  = !node.lastHeartbeat ? '#8a91a4' : isOnline ? '#00e676' : '#FF5722';
                        const isSelected = activeSensors.includes(node.sid) || activeSensors.includes(String(node.sid).toLowerCase()) || activeSensors.includes(String(node.sid).toUpperCase());
                        return (
                            <div key={node.sid} onClick={() => onSensorClick(String(node.sid).toLowerCase())}
                                style={{ display:'flex', justifyContent:'space-between', alignItems:'center', padding:'7px 8px', marginBottom:'3px', borderRadius:'6px', cursor:'pointer', backgroundColor: isSelected?'#1a3a2a':'transparent', border:`1px solid ${isSelected?'#1a3a2a':'#f0f0f0'}`, transition:'background-color 0.15s' }}
                                onMouseEnter={e=>{ if(!isSelected) e.currentTarget.style.backgroundColor='#f0f5f2'; }}
                                onMouseLeave={e=>{ if(!isSelected) e.currentTarget.style.backgroundColor='transparent'; }}
                            >
                                <div style={{ display:'flex', alignItems:'center', gap:'8px' }}>
                                    <span style={{ color:dotColor, fontSize:'12px' }}>●</span>
                                    <span style={{ fontWeight:'bold', fontSize:'13px', color: isSelected?'white':'#333' }}>{node.displayId}</span>
                                </div>
                                <div style={{ display:'flex', alignItems:'center', gap:'6px' }}>
                                    <span style={{ fontSize:'10px', color: isSelected?'#a0d0b0':(node.lastHeartbeat?'#888':'#FF5722'), fontFamily:'monospace', fontStyle: node.lastHeartbeat?'normal':'italic' }}>
                                        {node.lastHeartbeat ?? 'OFFLINE'}
                                    </span>
                                    {isSelected && <span style={{ color:'#00e676', fontSize:'12px' }}>✓</span>}
                                </div>
                            </div>
                        );
                    })}
                </div>

            </div>

            {/* ── GLYPH LEGEND — bottom-left, above timeline ──
                Shows the active colour scale (gradient bar with live
                min/max labels) and the fixed size-bucket legend for
                whichever variable isn't driving colour. Also hosts the
                on/off toggle for the barycentric interpolation overlay. */}
            <div style={{ position:'absolute', bottom:160, left:20, zIndex:1000, backgroundColor:'rgba(255,255,255,0.97)', padding:'14px 16px', borderRadius:'12px', boxShadow:'0 8px 24px rgba(0,0,0,0.15)', width:'222px' }}>

                {/* Header + Temp/Moisture toggle */}
                <div style={{ display:'flex', justifyContent:'space-between', alignItems:'center', borderBottom:'2px solid #eaeaea', paddingBottom:'8px', marginBottom:'10px' }}>
                    <span style={{ fontSize:'11px', fontWeight:'bold', color:'#1a3a2a', letterSpacing:'0.5px' }}>GLYPH LEGEND</span>
                    <div style={{ display:'flex', gap:'3px', backgroundColor:'#e9ecef', padding:'3px', borderRadius:'5px' }}>
                        {[['Temp','temp'],['Moisture','watermark']].map(([label, val]) => (
                            <button key={val} onClick={() => { setGlyphMode(val); setInterpOn(false); }}
                                style={{ border:'none', padding:'3px 9px', fontSize:'10px', fontWeight:'bold', borderRadius:'3px', cursor:'pointer', backgroundColor: glyphMode===val ? '#1a3a2a' : 'transparent', color: glyphMode===val ? 'white' : '#888', boxShadow: glyphMode===val ? '0 1px 3px rgba(0,0,0,0.2)' : 'none', transition:'all 0.15s', whiteSpace:'nowrap' }}
                            >{label}</button>
                        ))}
                    </div>
                </div>

                {glyphMode === 'temp' ? (
                    <>
                        <div style={{ fontSize:'10px', color:'#555', fontWeight:'bold', marginBottom:'6px' }}>🌡 Colour → Temperature (°C)</div>
                        <div style={{ marginBottom:'14px' }}>
                            <GradientScale
                                colors={TEMP_BASE_COLORS.map(rgbToHex)}
                                labels={domainLabels(tempDomain, 6, (tempDomain[1] - tempDomain[0]) <= 5 ? 1 : 0, '°')}
                            />
                        </div>
                        <div style={{ fontSize:'10px', color:'#555', fontWeight:'bold', marginBottom:'8px' }}>💧 Size → Watermark (cb)</div>
                        <div style={{ display:'flex', gap:'10px', alignItems:'flex-end', paddingLeft:'4px', marginBottom:'12px' }}>
                            {[[6,'≤ 20'],[10,'20–50'],[14,'50–100'],[18,'> 100']].map(([r,label])=>(
                                <div key={label} style={{ display:'flex', flexDirection:'column', alignItems:'center', gap:'4px' }}>
                                    <div style={{ width:r*2, height:r*2, borderRadius:'50%', backgroundColor:rgbToHex(WATERMARK_BASE_COLORS[0]), border:'2px solid rgba(0,0,0,0.35)', flexShrink:0 }}/>
                                    <span style={{ fontSize:'9px', color:'#777', textAlign:'center', lineHeight:'1.2' }}>{label}</span>
                                </div>
                            ))}
                        </div>
                        <div style={{ fontSize:'9px', color:'#aaa', fontStyle:'italic', marginBottom:'10px' }}>Larger = drier soil</div>
                    </>
                ) : (
                    <>
                        <div style={{ fontSize:'10px', color:'#555', fontWeight:'bold', marginBottom:'6px' }}>💧 Colour → Watermark (cb)</div>
                        <div style={{ marginBottom:'6px' }}>
                            <GradientScale
                                colors={WATERMARK_BASE_COLORS.map(rgbToHex)}
                                labels={domainLabels(watermarkDomain, 5, 0, '')}
                            />
                        </div>
                        <div style={{ display:'flex', justifyContent:'space-between', fontSize:'9px', color:'#999', marginBottom:'10px' }}>
                            <span>Wet</span><span>Very dry</span>
                        </div>
                        <div style={{ fontSize:'10px', color:'#555', fontWeight:'bold', marginBottom:'8px' }}>🌡 Size → Temperature (°C)</div>
                        <div style={{ display:'flex', gap:'10px', alignItems:'flex-end', paddingLeft:'4px', marginBottom:'12px' }}>
                            {[[6,'≤ 6°'],[10,'6–14°'],[14,'14–22°'],[18,'> 22°']].map(([r,label])=>(
                                <div key={label} style={{ display:'flex', flexDirection:'column', alignItems:'center', gap:'4px' }}>
                                    <div style={{ width:r*2, height:r*2, borderRadius:'50%', backgroundColor:rgbToHex(TEMP_BASE_COLORS[8]), border:'2px solid rgba(0,0,0,0.35)', flexShrink:0 }}/>
                                    <span style={{ fontSize:'9px', color:'#777', textAlign:'center', lineHeight:'1.2' }}>{label}</span>
                                </div>
                            ))}
                        </div>
                        <div style={{ fontSize:'9px', color:'#aaa', fontStyle:'italic', marginBottom:'10px' }}>Larger = hotter</div>
                    </>
                )}

                {/* Interpolation on/off toggle — shared by both modes */}
                <div style={{ borderTop:'1px solid #eaeaea', paddingTop:'10px' }}>
                    <div style={{ display:'flex', justifyContent:'space-between', alignItems:'center' }}>
                        <span style={{ fontSize:'10px', color:'#555', fontWeight:'bold' }}>
                            🎨 Gradient interpolation
                        </span>
                        <button
                            onClick={() => setInterpOn(v => !v)}
                            style={{
                                border: 'none', borderRadius:'12px', cursor:'pointer',
                                padding:'3px 10px', fontSize:'10px', fontWeight:'bold',
                                backgroundColor: interpOn ? '#1a3a2a' : '#e9ecef',
                                color: interpOn ? 'white' : '#888',
                                boxShadow: interpOn ? '0 1px 4px rgba(0,0,0,0.25)' : 'none',
                                transition:'all 0.2s',
                            }}
                        >{interpOn ? 'ON' : 'OFF'}</button>
                    </div>
                    {/* No separate gradient bar here on purpose — when interpolation
                        is on, the fill uses the exact same Temp/Moisture colour scale
                        already shown above, so repeating it would just be a duplicate. */}
                    {interpOn && (
                        <div style={{ marginTop:'8px', fontSize:'9px', color:'#aaa', fontStyle:'italic' }}>
                            Barycentric fill · uses the {glyphMode === 'temp' ? 'Temperature' : 'Moisture'} scale above
                        </div>
                    )}
                </div>
            </div>

            {/* Leaflet map — layer stack from bottom to top is roughly:
                tile layer, interaction handler, interpolation canvas,
                hull outline, Delaunay mesh, slice path, sensor markers. */}
            <style>{`
                @keyframes idw-spin {
                    from { stroke-dashoffset: 0; }
                    to   { stroke-dashoffset: -24; }
                }
                .idw-glyph-ring {
                    animation: idw-spin 0.8s linear infinite;
                }
                .leaflet-container {
                    cursor: pointer !important;
                }
                .leaflet-dragging .leaflet-container {
                    cursor: grabbing !important;
                }
                .map-is-loading, .map-is-loading .leaflet-container {
                    cursor: wait !important;
                }
            `}</style>
            <MapContainer
                center={[52.37, -3.77]}
                zoom={14}
                className={isBusy ? 'map-is-loading' : ''}
                style={{ width:'100%', height:'100%', zIndex:1, cursor: isBusy ? 'wait' : 'pointer' }}
            >
                <TileLayer attribution='&copy; OpenStreetMap' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/>
                <MapInteraction modeRef={modeRef} onMapClick={onSensorClick} currentDayDataRef={currentDayDataRef} setInterpolatedData={setInterpolatedData} glyphModeRef={glyphModeRef} hullPolygonRef={hullPolygonRef} tempDomainRef={tempDomainRef} watermarkDomainRef={watermarkDomainRef}/>

                {/* Barycentric interpolation canvas overlay — active when interpOn is true */}
                {useMemo(() => (
                <InterpolationCanvas
                    triangles={triangles}
                    glyphMode={glyphMode}
                    visible={interpOn}
                    domains={{ temp: tempDomain, watermark: watermarkDomain }}
                    onDrawComplete={handleDrawComplete}
                />
                ), [triangles, glyphMode, interpOn, tempDomain, watermarkDomain, handleDrawComplete])}

                {/* Convex hull boundary — defines the IDW interpolation zone */}
                {hullPolygon.length >= 3 && (
                    <Polygon
                        positions={hullPolygon}
                        color="#1a3a2a"
                        weight={1.5}
                        opacity={0.5}
                        fillColor="#1a3a2a"
                        fillOpacity={0.04}
                        dashArray="6 5"
                        interactive={false}
                    />
                )}

                {/* Delaunay mesh wireframe — hidden when interpolation canvas is active */}
                {!interpOn && meshEdges.map((edge, i) => (
                    <Polyline
                        key={`mesh-${i}`}
                        positions={edge}
                        color="#1a3a2a"
                        weight={1}
                        opacity={0.35}
                        dashArray="4 6"
                        interactive={false}
                    />
                ))}

                {/* Slice path — visible only in slice mode.
                    Each entry in activeSensors is either a "lat,lng" coordinate string
                    (from a map click or sensor click in slice mode) or a sensor ID fallback. */}
                {mode === 'slice' && (() => {
                    const slicePositions = activeSensors.map(item => {
                        // Coordinate string — "52.3729,-3.7716"
                        if (typeof item === 'string' && item.includes(',')) {
                            const parts = item.split(',').map(Number);
                            if (parts.length === 2 && !isNaN(parts[0]) && !isNaN(parts[1])) {
                                return parts; // [lat, lng]
                            }
                        }
                        // Sensor ID fallback
                        const s = allSensors.find(s =>
                            [s.sensor_id, String(s.sensor_id||'').toLowerCase(), String(s.sensor_id||'').toUpperCase(),
                             s.id,         String(s.id||'').toLowerCase(),         String(s.id||'').toUpperCase()]
                            .includes(item)
                        );
                        return s?.lat != null ? [s.lat, s.lon] : null;
                    }).filter(Boolean);

                    return (
                        <>
                            {/* Dashed path line */}
                            {slicePositions.length > 1 && (
                                <Polyline
                                    positions={slicePositions}
                                    color="#FF4500"
                                    weight={3}
                                    dashArray="10 7"
                                    opacity={0.85}
                                    interactive={false}
                                />
                            )}
                            {/* Waypoint anchor dots */}
                            {slicePositions.map((pos, i) => (
                                <CircleMarker
                                    key={`waypoint-${i}`}
                                    center={pos}
                                    radius={5}
                                    fillColor="#FF4500"
                                    color="white"
                                    weight={2}
                                    fillOpacity={1}
                                    interactive={false}
                                />
                            ))}
                        </>
                    );
                })()}

                {allSensors.map(masterSensor => {
                    // Each sensor marker: colour/radius come from
                    // getGlyphStyle for the current day + glyph mode;
                    // clicking behaves differently per mode (drops a
                    // waypoint at the sensor's coords in slice mode, or
                    // toggles the sensor ID in sensor mode).
                    if (masterSensor.lat == null || masterSensor.lon == null) return null;
                    const sidRaw   = masterSensor.sensor_id || masterSensor.id;
                    if (!sidRaw) return null;
                    const sidUpper = String(sidRaw).toUpperCase();
                    const sidLower = String(sidRaw).toLowerCase();

                    const dayData = currentDayData
                        ? (currentDayData[sidRaw] || currentDayData[sidLower] || currentDayData[sidUpper])
                        : null;

                    const { color, radius, offline, stale } = getGlyphStyle(dayData, glyphMode, { temp: tempDomain, watermark: watermarkDomain });
                    const isActive = [sidRaw, sidLower, sidUpper].some(id => activeSensors.includes(id));

                    return (
                        <CircleMarker
                            key={`marker-${sidRaw}-${glyphMode}-${currentDate}`}
                            center={[masterSensor.lat, masterSensor.lon]}
                            radius={isActive ? radius + 4 : radius}
                            fillColor={color}
                            color={isActive ? '#1a3a2a' : (stale ? '#8a91a4' : '#ffffff')}
                            weight={isActive ? 3 : (stale ? 2 : 2)}
                            opacity={isActive ? 1 : (stale ? 0.85 : 0.95)}
                            dashArray={stale ? '3 2' : undefined}
                            fillOpacity={offline ? 0.35 : (stale ? 0.55 : 0.85)}
                            eventHandlers={{ click: () => mode === 'slice'
                                ? onSensorClick(`${masterSensor.lat},${masterSensor.lon}`)
                                : onSensorClick(sidLower)
                            }}
                        >
                            <Popup offset={[0,-5]}>
                                <div style={{ textAlign:'center', minWidth:'140px', margin:'4px' }}>
                                    <strong style={{ fontSize:'15px', display:'block', color:'#3a1f1a', borderBottom:'2px solid #eaeaea', paddingBottom:'6px', marginBottom:'8px' }}>NODE: {sidUpper}</strong>
                                    {offline ? (
                                        <div style={{ fontSize:'13px', color:'#8a91a4', fontStyle:'italic', padding:'8px 0' }}>⚠️ No data in this range</div>
                                    ) : (
                                        <>
                                            {stale && (
                                                <div style={{ fontSize:'11px', color:'#c90086', fontStyle:'italic', marginBottom:'6px' }}>
                                                    ⚠️ {dayData.__isFuture ? 'Next available' : 'Last available'} reading — {dayData.__sourceDate}
                                                </div>
                                            )}
                                            <div style={{ display:'flex', alignItems:'center', justifyContent:'center', gap:'6px', marginBottom:'6px' }}>
                                                <div style={{ width:12, height:12, borderRadius:'50%', backgroundColor:color, border:'1px solid #ccc' }}/>
                                                <span style={{ fontSize:'14px', color:'#333', fontWeight:'bold' }}>🌡 {dayData.temp != null ? `${dayData.temp}°C` : 'N/A'}</span>
                                            </div>
                                            <div style={{ fontSize:'13px', color:'#050505ef', fontWeight:'bold' }}>💧 {dayData.watermark != null ? `${dayData.watermark} cb` : 'N/A'}</div>
                                            <div style={{ fontSize:'10px', color:'#130202', marginTop:'6px' }}>Size reflects {glyphMode === 'watermark' ? 'temperature' : 'soil moisture'}</div>
                                        </>
                                    )}
                                </div>
                            </Popup>
                            <Tooltip direction="top" offset={[0,-10]} opacity={0.95}>
                                <div style={{ textAlign:'center', minWidth:'110px', margin:'-2px' }}>
                                    <strong style={{ fontSize:'13px', display:'block', color:'#1a3a2a', borderBottom:'1px solid #ddd', paddingBottom:'3px', marginBottom:'4px' }}>{sidUpper}</strong>
                                    {offline ? (
                                        <div style={{ fontSize:'11px', color:'#8a91a4', fontStyle:'italic' }}>No data in range</div>
                                    ) : (
                                        <>
                                            {stale && (
                                                <div style={{ fontSize:'10px', color:'#000000', fontStyle:'italic', marginBottom:'2px' }}>
                                                    {dayData.__isFuture ? 'next' : 'last'} available · {dayData.__sourceDate}
                                                </div>
                                            )}
                                            <div style={{ fontSize:'12px', fontWeight:'bold', color: color }}>🌡 {dayData.temp != null ? `${dayData.temp}°C` : 'N/A'}</div>
                                            <div style={{ fontSize:'12px', fontWeight:'bold', color: glyphMode === 'watermark' ? color : '#03A9F4' }}>💧 {dayData.watermark != null ? `${dayData.watermark} cb` : 'N/A'}</div>
                                        </>
                                    )}
                                </div>
                            </Tooltip>
                        </CircleMarker>
                    );
                })}
            </MapContainer>

            {/* Windy-style timeline */}
            {dates.length > 0 && (
                <WindyTimeline
                    dates={dates}
                    currentIndex={currentIndex}
                    setCurrentIndex={setCurrentIndex}
                    isPlaying={isPlaying}
                    setIsPlaying={setIsPlaying}
                    playSpeed={playSpeed}
                    setPlaySpeed={setPlaySpeed}
                />
            )}
        </div>
    );
}

// ─── WINDY-STYLE SCROLLABLE TIMELINE ────────────────────────────────────────
// Pixel width of one timeline step (one data point / date-hour tick).
const PX_PER_STEP = 48;

/**
 * WindyTimeline — horizontally-scrollable/draggable date scrubber styled
 * after the Windy.com weather app's timeline. Renders day-group headers,
 * hourly tick marks, a play/pause button with speed presets, and a
 * "needle" marking the currently-selected date/time. Supports both
 * click-to-jump and click-and-drag scrolling.
 */
function WindyTimeline({ dates, currentIndex, setCurrentIndex, isPlaying, setIsPlaying, playSpeed, setPlaySpeed }) {
    const trackRef       = useRef(null); // the scrollable track div
    const isDragging     = useRef(false);
    const dragStartX     = useRef(0);
    const dragStartScroll= useRef(0);

    // Drag-to-scroll handlers, shared between mouse and touch events.
    const startDrag = (clientX) => {
        isDragging.current    = true;
        dragStartX.current    = clientX;
        dragStartScroll.current = trackRef.current.scrollLeft;
    };
    const moveDrag = (clientX) => {
        if (!isDragging.current) return;
        trackRef.current.scrollLeft = dragStartScroll.current - (clientX - dragStartX.current);
    };
    const endDrag = () => { isDragging.current = false; };

    // Distinguishes a genuine click (jump to that date) from the end of a
    // drag gesture — only treats it as a click if the pointer barely
    // moved from where the drag started.
    const handleTrackClick = (e) => {
        if (Math.abs(e.clientX - dragStartX.current) > 4) return;
        const rect = trackRef.current.getBoundingClientRect();
        const clickX = e.clientX - rect.left + trackRef.current.scrollLeft;
        setCurrentIndex(Math.max(0, Math.min(dates.length - 1, Math.round(clickX / PX_PER_STEP))));
        setIsPlaying(false);
    };

    // Day header groups
    // Groups consecutive timeline steps that fall on the same calendar
    // day, so a single "Mon 14 Jul" label can span all of that day's ticks.
    const dayGroups = useMemo(() => {
        const groups = [];
        let cur = null;
        dates.forEach((iso, idx) => {
            const key = new Date(iso).toDateString();
            if (!cur || cur.key !== key) {
                cur = { key, label: new Date(iso).toLocaleDateString('en-GB', { weekday:'short', day:'numeric', month:'short' }), startIdx: idx, count: 1 };
                groups.push(cur);
            } else { cur.count++; }
        });
        return groups;
    }, [dates]);

    // Hourly tick labels
    // Only labels a tick with "HH:00" when the hour differs from the
    // previous step's hour, so labels don't repeat on every single tick.
    const hourTicks = useMemo(() => dates.map((iso, idx) => {
        const d   = new Date(iso);
        const hrs = d.getHours();
        const prevHr = idx > 0 ? new Date(dates[idx-1]).getHours() : -1;
        return { idx, label: hrs !== prevHr ? `${String(hrs).padStart(2,'0')}:00` : null };
    }), [dates]);

    const pad2    = n => String(n).padStart(2,'0');
    const needleLabel = (iso) => { if (!iso) return ''; const d=new Date(iso); return `${pad2(d.getHours())}:${pad2(d.getMinutes())}`; };
    const totalW  = dates.length * PX_PER_STEP;

    return (
        <div style={{ position:'absolute', bottom:0, left:0, right:0, zIndex:1000, backgroundColor:'#1e2126', userSelect:'none' }}>

            {/* Speed bar */}
            <div style={{ display:'flex', alignItems:'center', justifyContent:'flex-end', gap:'6px', padding:'5px 14px', borderBottom:'1px solid #2e3338' }}>
                <span style={{ fontSize:'10px', color:'#555', fontWeight:'bold' }}>SPEED</span>
                {[{ label:'0.5×', ms:1600 },{ label:'1×', ms:800 },{ label:'2×', ms:400 },{ label:'4×', ms:200 }].map(opt=>(
                    <button key={opt.ms} onClick={()=>setPlaySpeed(opt.ms)} style={{ padding:'3px 8px', fontSize:'10px', fontWeight:'bold', border:'none', borderRadius:'4px', cursor:'pointer', backgroundColor: playSpeed===opt.ms?'#c8f04a':'#2e3338', color: playSpeed===opt.ms?'#1a1a1a':'#aaa', transition:'all 0.15s' }}>{opt.label}</button>
                ))}
            </div>

            {/* Play button + scrollable track */}
            <div style={{ display:'flex', alignItems:'stretch' }}>

                {/* Fixed play button */}
                <div style={{ display:'flex', flexDirection:'column', alignItems:'center', justifyContent:'center', padding:'0 14px', borderRight:'1px solid #2e3338', flexShrink:0, gap:'4px', minWidth:'58px' }}>
                    <button onClick={()=>setIsPlaying(p=>!p)}
                        style={{ backgroundColor:'transparent', color:'white', border:'2px solid #555', borderRadius:'50%', width:'36px', height:'36px', display:'flex', justifyContent:'center', alignItems:'center', cursor:'pointer', fontSize:'15px' }}
                    >{isPlaying?'⏸':'▶'}</button>
                    <span style={{ fontSize:'9px', color:'#888', fontFamily:'monospace', whiteSpace:'nowrap' }}>{needleLabel(dates[currentIndex])}</span>
                </div>

                {/* Scrollable track */}
                <div
                    ref={trackRef}
                    style={{ flex:1, overflowX:'auto', overflowY:'hidden', cursor:'grab', scrollbarWidth:'none', msOverflowStyle:'none' }}
                    onMouseDown={e=>startDrag(e.clientX)}
                    onMouseMove={e=>moveDrag(e.clientX)}
                    onMouseUp={e=>{endDrag(); handleTrackClick(e);}}
                    onMouseLeave={endDrag}
                    onTouchStart={e=>startDrag(e.touches[0].clientX)}
                    onTouchMove={e=>moveDrag(e.touches[0].clientX)}
                    onTouchEnd={endDrag}
                >
                    <div style={{ position:'relative', width:`${totalW}px`, height:'68px' }}>

                        {/* Day labels */}
                        {dayGroups.map(g=>(
                            <div key={g.key} style={{ position:'absolute', top:0, height:'20px', left:`${g.startIdx*PX_PER_STEP}px`, width:`${g.count*PX_PER_STEP}px`, borderLeft:'1px solid #444', display:'flex', alignItems:'center', paddingLeft:'6px', boxSizing:'border-box', pointerEvents:'none' }}>
                                <span style={{ fontSize:'11px', fontWeight:'bold', color:'#c8f04a', whiteSpace:'nowrap' }}>{g.label}</span>
                            </div>
                        ))}

                        {/* Hour ticks */}
                        {hourTicks.map(({idx,label})=>(
                            <div key={idx} style={{ position:'absolute', top:'20px', left:`${idx*PX_PER_STEP}px`, width:`${PX_PER_STEP}px`, height:'48px', borderLeft: label?'1px solid #3a3d42':'none', boxSizing:'border-box', pointerEvents:'none' }}>
                                {label && <span style={{ position:'absolute', top:'4px', left:'4px', fontSize:'10px', color:'#888', whiteSpace:'nowrap' }}>{label}</span>}
                                <div style={{ position:'absolute', bottom:'6px', left:0, width:'1px', height:'6px', backgroundColor:'#3a3d42' }}/>
                            </div>
                        ))}

                        {/* Current-time needle */}
                        <div style={{ position:'absolute', top:0, bottom:0, left:`${currentIndex*PX_PER_STEP}px`, width:'2px', backgroundColor:'#c8f04a', zIndex:10, pointerEvents:'none' }}>
                            <div style={{ position:'absolute', top:'20px', left:'50%', transform:'translateX(-50%)', backgroundColor:'#c8f04a', color:'#1a1a1a', fontSize:'10px', fontWeight:'bold', padding:'2px 5px', borderRadius:'3px', whiteSpace:'nowrap' }}>
                                {needleLabel(dates[currentIndex])}
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div style={{ textAlign:'center', fontSize:'9px', color:'#3a3d42', padding:'3px 0', letterSpacing:'0.5px' }}>
                Drag timeline to scroll · Click to jump
            </div>
        </div>
    );
}